---
abstract: 'Create customised X11 terminal windows'
author:
  - 'Evan Giles <egiles@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: X11-Terminal
provides:
  X11::Terminal:
    file: lib/X11/Terminal.pm
    version: v1.0.0
  X11::Terminal::GnomeTerminal:
    file: lib/X11/Terminal/GnomeTerminal.pm
    version: v1.0.0
  X11::Terminal::Konsole:
    file: lib/X11/Terminal/Konsole.pm
    version: v1.0.0
  X11::Terminal::XTerm:
    file: lib/X11/Terminal/XTerm.pm
    version: v1.0.0
requires:
  Moose: 0.54
  perl: v5.6.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/egiles/x11-terminal
version: v1.0.0
